language: r
cache: packages

r_github_packages:
  - wilkelab/cowplot
  - ropensci/magick

repos:
  rforge: http://R-Forge.R-project.org
  
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev

after_success:
  - Rscript -e 'covr::codecov()'
